### ISSUE TITLE
References to http_proxy and https_proxy (using squid)

### ISSUE THREAD

**Issue by bmw-bharm** [kentrikos/template-environment-configuration#13]
For most of the references to http_proxy and https_proxy (using squid) we only require one value for the target proxy. Essentially we only need one value for this which can be inserted for both ENV values. 

Removing the other fields will simplify the configuration options. Also, this value is referenced many times during the various deployment phases. (BH, Jenkins-core and K8S). It would be nice to preserve this value during the automation and reduce the potential for a user to make a mistake while entering the values more than once.

**Comment by henrikandersson-bmw** [comment]
Nice to have feature if your proxy is the same for http and https, but to keep this generic we leave this as is for now.
